import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import FooterSection from "@/components/footerSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}   
      >
   <div className="p-7 mx-2">
  <Navbar isLoggedIn={true} userName="Nikhil" />
</div>


        {children}
     <FooterSection/>   
      </body>
    </html>
  );
}


{/* <Navbar
  isLoggedIn={user !== null} // or your auth state
  userName={user?.fullName}
  userAvatar={user?.profilePic}
/> */}



//hydration learning in the react for passing argument in the 
// div so that the work will be happen 