import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import FooterSection from "@/components/footerSection";
import Providers from "../store/provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tutors Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Redux Provider */}
        <Providers>
          {/* Navbar (uses Redux internally) */}
          <div className="p-7 mx-2">
            <Navbar />
          </div>

          {/* Page content */}
          {children}

          {/* Toasts */}
          <Toaster richColors position="top-right" />

          {/* Footer */}
          <FooterSection />
        </Providers>
      </body>
    </html>
  );
}
